const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getCategories: () => ipcRenderer.invoke('get-categories'),
  getProductsByCategory: (category) => ipcRenderer.invoke('get-products-by-category', category),
  getAllProducts: () => ipcRenderer.invoke('get-all-products'),
  createSale: (data) => ipcRenderer.invoke('create-sale', data),
  updateStock: (data) => ipcRenderer.invoke('update-stock', data),
  getSales: () => ipcRenderer.invoke('get-sales'),
  getSaleDetail: (saleId) => ipcRenderer.invoke('get-sale-detail', saleId),
  getCierre: (data) => ipcRenderer.invoke('get-cierre', data),
  confirmarCierre: (data) => ipcRenderer.invoke('confirmar-cierre', data),
  getHistorialCierres: () => ipcRenderer.invoke('get-historial-cierres'),
  getTodayTotal: (usuario_id) => ipcRenderer.invoke('get-today-total', usuario_id),
  getPendientes: () => ipcRenderer.invoke('get-pendientes'),
  cobrarPendiente: (data) => ipcRenderer.invoke('cobrar-pendiente', data),
  getCobros: (venta_id) => ipcRenderer.invoke('get-cobros', venta_id),
  login: (data) => ipcRenderer.invoke('login', data),
  getUsers: () => ipcRenderer.invoke('get-users'),
  createUser: (data) => ipcRenderer.invoke('create-user', data),
  deleteUser: (userId) => ipcRenderer.invoke('delete-user', userId),
  updateProduct: (data) => ipcRenderer.invoke('update-product', data),
  createProduct: (data) => ipcRenderer.invoke('create-product', data),
  deleteProduct: (id) => ipcRenderer.invoke('delete-product', id),
  addMovimientoCaja: (data) => ipcRenderer.invoke('add-movimiento-caja', data),
  getMovimientosCaja: (data) => ipcRenderer.invoke('get-movimientos-caja', data),
  deleteMovimientoCaja: (id) => ipcRenderer.invoke('delete-movimiento-caja', id),
  abrirCaja: (data) => ipcRenderer.invoke('abrir-caja', data),
  getApertura: (usuario_id) => ipcRenderer.invoke('get-apertura', usuario_id),
  getEstaCerrado: (usuario_id) => ipcRenderer.invoke('get-esta-cerrado', usuario_id),
  resetDatabase: () => ipcRenderer.invoke('reset-database'),
});
